language: ruby
bundler_args: --without development production staging
rvm:
  - 2.1.1
addons:
  postgresql: 9.3
# uncomment this line if your project needs to run something other than `rake`:
before_script:
  - psql -c 'create database sapi_test' -U postgres
script:
  - CODECLIMATE_REPO_TOKEN=7ee3093908aa296e3db98e6e00cd28db3f8dd802d932f2dc218eb954c73c6402 bundle exec rake
notifications:
  slack: wcmc:38bMoeEC28Tm3cnSGmhdGYVh
