# docker-compose.yml
version: '3.8'

networks:
  sapi:
    driver: bridge
    external: true

services:
  api:
    container_name: species-api-rails
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ./bin/docker-entrypoint
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: &rails_volumes
      # Used for both rails and sidekiq

      # The following paths are commonly written by the application at runtime
      - 'app_tmp:/species-api/tmp'
      - 'app_log:/species-api/log'
      - 'app_storage:/species-api/storage'

      # The following paths are writable during build/development
      - './Gemfile.lock:/species-api/Gemfile.lock'

      # Most rest of the application should not be writable, except to run
      # specific tasks like db migrations
      - './app:/species-api/app:${SAPI_CONTAINER_FS_MODE:-ro}'
      - './bin:/species-api/bin:${SAPI_CONTAINER_FS_MODE:-ro}'
      - './config:/species-api/config:${SAPI_CONTAINER_FS_MODE:-ro}'
      - './db:/species-api/db:${SAPI_CONTAINER_FS_MODE:-ro}'
      - './db_init:/species-api/db_init:${SAPI_CONTAINER_FS_MODE:-ro}'
      - './doc:/species-api/doc:${SAPI_CONTAINER_FS_MODE:-ro}'
      - './lib:/species-api/lib:${SAPI_CONTAINER_FS_MODE:-ro}'
      - './script:/species-api/script:${SAPI_CONTAINER_FS_MODE:-ro}'
      - './spec:/species-api/spec:${SAPI_CONTAINER_FS_MODE:-ro}'
      - './vendor:/species-api/vendor:${SAPI_CONTAINER_FS_MODE:-ro}'

      # During deploy public/assets is removed and re-added
      - './public:/species-api/public'
      - '.:/species-api'

      # Keep the cache of bundler gems for sharing across install commands
      - bundler_gems:/usr/local/bundle
    ports:
      - '${SPECIES_API_CONTAINER_RAILS_PORT:-3011}:3000'
    networks:
      - sapi
    stdin_open: true
    tty: true
    environment:
      MAILER_ADDRESS: sapi-mailcatcher
      MEMCACHE_SERVERS: sapi-memcached:11211
      SPECIES_API_DATABASE_HOST: sapi-db
      SPECIES_API_DATABASE_USERNAME: postgres
      SPECIES_API_DATABASE_PORT: 5432
      SPECIES_API_SIDEKIQ_REDIS_URL: redis://sapi-redis:6379/1
      CAPTIVE_BREEDING_DATABASE_HOST: sapi-db

  api-sidekiq:
    container_name: species-api-sidekiq
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - sapi
    command: /bin/bash -l -c "bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    volumes: *rails_volumes
    environment:
      MAILER_ADDRESS: sapi-mailcatcher
      MEMCACHE_SERVERS: sapi-memcached:11211
      SPECIES_API_DATABASE_HOST: sapi-db
      SPECIES_API_DATABASE_USERNAME: postgres
      SPECIES_API_DATABASE_PORT: 5432
      SPECIES_API_SIDEKIQ_REDIS_URL: redis://sapi-redis:6379/1

volumes:
  bundler_gems:
  app_tmp:
  app_log:
  app_storage:
  app_private_elibrary:
  app_public_uploads:
  app_public_downloads:
  app_spec_public:

secrets:
  host_ssh_key:
    file: ~/.ssh/id_ed25519
  host_ssh_config:
    file: ~/.ssh/config
