default: &defaults
  # Your app's name
  name: "Species+ API"
  active: false

  # Your push api key, it is possible to set this dynamically using ERB:
  # push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"

  # Actions that should not be monitored by AppSignal
  ignore_actions:
    - "Rails::HealthController#show" # GET /up

  ignore_exceptions:
    - ActiveRecord::RecordNotFound

  ignore_errors:
    - ActiveRecord::RecordNotFound

  # The cuttoff point in ms above which a request is considered slow, default is 200
  # slow_request_threshold: 200

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
production:
  <<: *defaults
  active: true

staging:
  <<: *defaults
  active: true
