default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV.fetch("SPECIES_API_DATABASE_HOST")     { Rails.application.credentials.dig(:db, :host) || 'localhost' } %>
  username: <%= ENV.fetch("SPECIES_API_DATABASE_USERNAME") { Rails.application.credentials.dig(:db, :username) || 'postgres' } %>
  password: <%= ENV.fetch("SPECIES_API_DATABASE_PASSWORD") { Rails.application.credentials.dig(:db, :password) } %>
  port:     <%= ENV.fetch("SPECIES_API_DATABASE_PORT")     { Rails.application.credentials.dig(:db, :port) || '5432' } %>
  pool:     <%= ENV.fetch("SPECIES_API_RAILS_MAX_THREADS") { 5 } %>
  variables:
    lock_timeout: 10s

development:
  <<: *default
  database: sapi_development
  timeout: 5000

test:
  <<: *default
  database: sapi_species_api_test
  timeout: 5000

staging:
  <<: *default
  database: sapi_staging
  template: template0
  pool: <%= ENV.fetch("SPECIES_API_RAILS_MAX_THREADS") { 10 } %>

production:
  <<: *default
  database: sapi_production
  template: template0
  pool: <%= ENV.fetch("SPECIES_API_RAILS_MAX_THREADS") { 10 } %>
